server.port = 8024

#\uB8E8\uD2B8 \uD3F4\uB354
spring.thymeleaf.prefix=classpath:templates/thymeleaf/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

#thymeleaf \uD15C\uD50C\uB9BF\uC5D0 \uB300\uD55C \uCE90\uC2DC. \uAC1C\uBC1C\uC2DC\uC5D0 false, \uC6B4\uC601\uC2DC\uC5D0 true\uB85C \uBCC0\uACBD\uD558\uC5EC \uC0AC\uC6A9
spring.thymeleaf.cache=false

#\uD15C\uD50C\uB9BF \uC704\uCE58 \uC874\uC7AC \uD655\uC778 -template \uB514\uB809\uD1A0\uB9AC\uC5D0 \uD30C\uC77C\uC774 \uC788\uB294\uC9C0 \uC5C6\uB294\uC9C0 \uCCB4\uD06C, \uC5C6\uC73C\uBA74 \uC5D0\uB7EC\uB97C \uBC1C\uC0DD
spring.thymeleaf.check-template=true

# meta(<meta charset="UTF-8>), link \uB4F1\uC758 \uB2EB\uAE30 \uD0DC\uADF8\uAC00 \uC5C6\uC5B4 \uC624\uB958\uAC00 \uBC1C\uC0DD\uC2DC \uD14C\uC2A4\uD2B8\uC6A9 \uC635\uC158, \uC608\uC804 \uBC84\uC804 \uB610\uB294 \uC5C4\uACA9\uD55C \uCCB4\uD06C\uC5D0 \uC758\uD574 \uBC1C\uC0DD\uC2DC
# spring.thymeleaf.mode=LEGACYHTML5
# net.sourceforge.nekohtml:nekohtml
#
# spring.thymeleaf.mode=html
